DeviceModel:
  required:
    - id
    - type
    - category
    - controlledProperty
    - manufacturerName
    - brandName
    - modelName
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: 'This entity captures the static properties of a Device. '
  properties:
    alternateName:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/alternateName
    annotations:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/annotations

    brandName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: 'Device's brand name.'
      externalDocs: 
        url: "https://schema.org/brand"
    category:
      x-ngsi:
        type: Property
      type: array
      description: 'Device's category(ies).'
      items:
        allOf:
          - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/saref-terms.yaml#/Categories"
    color:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/color
    controlledProperty:
      x-ngsi:
        type: Property
      type: array
      description: |
        Anything that can be sensed, measured or controlled by.
      items:
        anyOf:
          - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/saref-terms.yaml#/ControlledProperties"
    dataProvider:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/dataProvider
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    deviceClass:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: |
        Class of constrained device as specified by RFC 7228. If the
        device is not a constrained device this property shall not be present.
      externalDocs: 
        url: "https://tools.ietf.org/html/rfc7228#section-3"
    documentation:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: 'A link to device's documentation.'
      format: uri
    energyLimitationClass:
      $ref: "https://raw.githubusercontent.com//smart-data-models/dataModel.Device/edit/master/DeviceModel/schema.yaml#/EnergyLimitationClass"
    function:
      x-ngsi:
        type: Property
      type: array
      description: |
        The functionality necessary to accomplish the task for which a
        Device is designed. A device can be designed to perform more than one
        function. Defined by [SAREF](https://w3id.org/saref#Function).
      items:
        anyOf:
          - $ref: "https://raw.githubusercontent.com//smart-data-models/dataModel.Device/edit/master/DeviceModel/schema.yaml#/Function"
    image:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/image
    manufacturerName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: 'Device's manufacturer name.'
      externalDocs: 
        url: "https://schema.org/model"
    modelName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: 'Device's model name.'
      externalDocs: 
        url: "https://schema.org/model"
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/owner
    source:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/source
    supportedProtocol:
      x-ngsi:
        type: Property
      type: array
      description: 'Supported protocol(s) or networks.'
      items:
        anyOf:
          - $ref: "https://raw.githubusercontent.com/smart-data-models/dataModel.Device/master/schema.yaml#/SupportedProtocol'
    supportedUnits:
      x-ngsi:
        type: Property
      type: array
      description: |
        Units of measurement supported by the device. Allowed values: The unit code (text) of measurement given using the
        [UN/CEFACT Common Code](http://wiki.goodrelations-vocabulary.org/Documentation/UN/CEFACT_Common_Codes)
        (max. 3 characters).
      items:
        type: string
                
Function: 
  description: |
  
    The functionality necessary to accomplish the task for which a
    Device is designed. A device can be designed to perform more than one
    function. Defined by [SAREF](https://w3id.org/saref#Function).
    
      -   `levelControl`
      -   `sensing`
      -   `onOff`
      -   `openClose`
      -   `metering`
      -   `eventNotification`
  enum: 
      -   levelControl
      -   sensing
      -   onOff
      -   openClose
      -   metering
      -   eventNotification
  type: string
  x-ngsi: 
    uri-prefix: "https://w3id.org/saref#"

EnergyLimitationClass:
  externalDocs: 
    url: "https://tools.ietf.org/html/rfc7228#section-3"
  description: |
    Device's class of energy limitation as per RFC 7228.
   
    -   `E0`
    -   `E1`
    -   `E2`
    -   `E9`
   enum:
     - E0
     - E1
     - E2
     - E9
  
