DeviceModel:
  required:
    - id
    - type
    - category
    - controlledProperty
    - manufacturerName
    - brandName
    - modelName
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: 'This entity captures the static properties of a Device. '
  properties:
    alternateName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    annotations:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
    brandName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    category:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          -  actuator
          -  beacon
          -  endgun
          -  HVAC
          -  implement
          -  irrSystem
          -  irrSection
          -  meter
          -  network
          -  multimedia
          -  sensor
    color:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    controlledProperty:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - temperature
          - humidity
          - light
          - motion
          - fillingLevel
          - occupancy
          - power
          - pressure
          - smoke
          - energy
          - airPollution
          - noiseLevel
          - weatherConditions
          - precipitation
          - windSpeed
          - windDirection
          - atmosphericPressure
          - solarRadiation
          - depth
          - pH
          - conductivity
          - conductance
          - tss
          - tds
          - turbidity
          - salinity
          - orp
          - cdom
          - waterPollution
          - location
          - speed
          - heading
          - weight
          - waterConsumption
          - gasComsumption
          - electricityConsumption
          - soilMoisture
          - trafficFlow
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    deviceClass:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    documentation:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: ''
      format: uri
    energyLimitationClass:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    function:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          - levelControl
          - sensing
          - onOff
          - openClose
          - metering
          - eventNotification
    image:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: ''
      format: uri
    manufacturerName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    modelName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        anyOf:
          - type: string
            minLength: 1
            maxLength: 256
            pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
          - type: string
            format: uri
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    supportedProtocol:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        enum:
          -  3g
          -  bluetooth
          -  "bluetooth LE"
          -  cat-m
          -  coap
          -  ec-gsm-iot
          -  gprs
          -  http
          -  lwm2m
          -  lora
          -  lte-m
          -  mqtt
          -  nb-iot
          -  onem2m
          -  sigfox
          -  ul20
          -  websocket    
    supportedUnits:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
