Device:
  required:
    - id
    - type
    - category
    - controlledProperty
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: >-
    An apparatus (hardware + software + firmware) intended to accomplish a
    particular task (sensing the environment, actuating, etc.).
  properties:
    address:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    alternateName:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/alternateName
    areaServed:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/areaServed
    category:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        allOf:
          - $ref: "./device.yaml#/DeviceCategory"
    configuration:
      x-ngsi:
        type: Property
      type: object
      description: ''
    controlledAsset:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        oneOf:
          - type: string
            format: uri
          - &ref_0
            anyOf:
              - type: string
                minLength: 1
                maxLength: 256
                pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
              - type: string
                format: uri
    controlledProperty:
      x-ngsi:
        type: Property
      type: array
      description: "See attribute `controlledProperty` from [DeviceModel](../../DeviceModel/doc/spec.md). Optional but recommended to optimize queries."
      items:
        anyOf:
          - $ref: "https://raw.githubusercontent.com/smart-data-models/data-models/master/saref-terms.yaml#/ControlledProperties"
    dataProvider:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/dataProvider
    dateFirstUsed:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    dateInstalled:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    dateLastCalibration:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    dateLastValueReported:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    dateManufactured:
      x-ngsi:
        type: Property
        model: 'https://schema.org/DateTime'
      type: string
      description: ''
      format: date-time
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    deviceState:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    firmwareVersion:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    hardwareVersion:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    ipAddress:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        oneOf:
          - format: ipv4
          - format: ipv6
    location:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    macAddress:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        type: string
        pattern: '^([[:xdigit:]]{2}[:.-]?){5}[[:xdigit:]]{2}$'
    mnc:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    osVersion:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    owner:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/owner
    provider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    serialNumber:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    softwareVersion:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    source:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/fiware-terms.yaml#/source
    supportedProtocol:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        anyOf:
          - $ref: "./device.yaml#/SupportedProtocol"
    value:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''

DeviceCategory:
  type: string
  x-ngsi: 
    uri-prefix: "https://uri.fiware.org/ns/data-models#"

  description: |
      -  `actuator`
      -  `beacon`
      -  `endgun`
      -  `HVAC`
      -  `implement`
      -  `irrSystem`
      -  `irrSection`
      -  `meter`
      -  `network`
      -  `multimedia`
      -  `sensor`
  items:
    type: string
    enum:
      -  actuator
      -  beacon
      -  endgun
      -  HVAC
      -  implement
      -  irrSystem
      -  irrSection
      -  meter
      -  network
      -  multimedia
      -  sensor


SupportedProtocol: 
  description: |
      -   `3g`
      -   `cat-m`
      -   `ec-gsm-iot`
      -   `grps`
      -   `http`
      -   `lora`
      -   `lte-m`
      -   `lwm2m`
      -   `mqtt`
      -   `nb-iot`
      -   `onem2m`
      -   `sigfox`
      -   `ul20`
      -   `websocket`
  enum: 
    - 3g
    - cat-m
    - ec-gsm-iot
    - grps
    - http
    - lora
    - lte-m
    - lwm2m
    - mqtt
    - nb-iot
    - onem2m
    - sigfox
    - ul20
    - websocket
  type: string
  x-ngsi: 
    uri-prefix: "https://uri.fiware.org/ns/data-models#"